restructured the custom text triggers and added a presentseffect.v1
HappyHub1/December pull request #19
Opened 2020-11-26 05:02 UTC by ShizuruAnon

2020-11-26 06:09 UTC, obto commented on december.js
> +            CustomTextTriggers.effect_lookup[message_parts[0]].handle(message_parts, [did_send_the_message]);
`handle()` needs to be updated to only take the args

2020-11-26 06:09 UTC, obto commented on december.js
> +        //CustomTextTriggers.effect_lookup['/padoru'].handle('', []);
Remove the testing code

2020-11-26 06:09 UTC, obto commented on december.js
> +            CustomTextTriggers.effect_lookup[effectCls.command] = {effect: effectCls, handle: effectCls.handleCommand};
```suggestion
        for (let effect_cls of CustomTextTriggers.effects) {
            effect_cls.init();
            CustomTextTriggers.effect_lookup[effect_cls.command] = {effect: effect_cls, handle: effect_cls.handleCommand};
```

2020-11-26 06:09 UTC, obto commented on december.js
> +            CustomTextTriggers.effect_lookup[effectCls.command] = {effect: effectCls, handle: effectCls.handleCommand};
Stick to camelCase for function names, and snake_case for variables

2020-11-26 06:09 UTC, obto commented on december.js
> +    static handleCommand(message_parts, did_send_the_message){
Instead of passing message parts as an array, lets explode this out into named arguments and defaults. E.g., `handleCommand(arg1='foo', arg2='bar');`

2020-11-26 06:09 UTC, obto commented on december.js
> +            CustomTextTriggers.effect_lookup[message_parts[0]].handle(message_parts, [did_send_the_message]);
1. We can also explode the args in here so the function declarations of each effect can use named variables

1. Also, `did_send_the_message` shouldnt be an array... right?

2020-11-27 03:29 UTC, ShizuruAnon commented on december.js
> +    static handleCommand(message_parts, did_send_the_message){
I'm not sure the best way to do that exactly in javascript as each handleCommand function (for the different effects) may need different things and we are passing all arguments to every handleCommand function. My idea for it was just to pass a dict with everything if you want them named.

2020-11-27 17:27 UTC, ShizuruAnon commented on december.js
> +        CustomTextTriggers.effect_lookup = {};
done in latest commits

2020-11-27 17:29 UTC, ShizuruAnon commented on december.js
> +            CustomTextTriggers.effect_lookup[message_parts[0]].handle(message_parts, [did_send_the_message]);
its just a bool. I had it in an array so I could add other args with it if needed. If we explode the args then this wont be an issue I dont think.

2020-11-29 00:09 UTC, obto commented on december.js
> +effectsbtn = $('<button id="effectsbtn" class="btn btn-sm ' + (EFFECTSOFF ? 'btn-danger' : 'btn-default') + '" title="Turn off effects">Effects OFF</button>')
Don't think we have to assign this to a variable. Unless this is an artifact from some of Happy's older code

2020-11-29 00:09 UTC, obto commented on december.js
> +            CustomTextTriggers.effect_lookup.get(effect_name).handle(...effect_args, did_send_the_message);
Since effect_args can be variable in length, we need to have required arguments at the front
```suggestion
            CustomTextTriggers.effect_lookup.get(effect_name).handle(did_send_the_message, ...effect_args);
```

2020-11-29 00:12 UTC, obto commented
Moving to explicitly stated (and exploded) arguments means there are a few more places that need to be modified. For example the erabe parsemessage function needs to be modified

I'll have to try and take a longer look tomorrow. Had to finish some of my own additions to this year today instead

2020-11-29 02:50 UTC, ShizuruAnon commented on december.js
> +effectsbtn = $('<button id="effectsbtn" class="btn btn-sm ' + (EFFECTSOFF ? 'btn-danger' : 'btn-default') + '" title="Turn off effects">Effects OFF</button>')
Yeah I was just converting some of happy's code to make it work.

2020-11-29 20:45 UTC, obto requested changes

2020-11-29 20:45 UTC, obto commented on december.js
> +    static _face_animation(){
Keep to the code style of the rest of the document. snake_case variables and camelCase functions

2020-11-29 20:45 UTC, obto commented on december.js
> +    }
Using `.bind` is fine but using `() => {}` is preferred

```suggestion
    static _run_presents_animation() {
        const create_fn = (is_left) => {
            if (!PresentsEffect.state.is_on) {
                return;
            }

            PresentsEffect._create_present(is_left);
            setTimeout(() => create_fn(!is_left), PresentsEffect.state.level.spawn_rate);
        };
        setTimeout(() => create_fn(true), PresentsEffect.state.level.spawn_rate);
    }
```

2020-11-29 20:45 UTC, obto commented on december.js
> +        else            { offset = 55; }
Follow the code style of the rest of the document

```suggestion
        if (is_left) {
            offset = 10;
        }
        else {
            offset = 55;
        }
```

2020-11-29 20:45 UTC, obto commented on december.js
> +        let random_location = (Math.random() * 35+ offset).toFixed(4);
```suggestion
        let random_location = (Math.random() * 35 + offset).toFixed(4);
```

2020-11-29 20:45 UTC, obto commented on december.js
> +        inner.classList.add('c-effect__presents-present-fall-'.concat(animation));
```suggestion
        inner.classList.add(`c-effect__presents-present-fall-${animation}`);
```

2020-11-29 20:45 UTC, obto commented on december.js
> +    static handleCommand(message_parts, otherArgs) { // for compatibility
```suggestion
    static handleCommand(message_parts = [], otherArgs = {}) { // for compatibility
```

2020-11-29 20:45 UTC, obto commented on december.js
> +    static handleCommand(message_parts, otherArgs) {
```suggestion
    static handleCommand(message_parts = [], otherArgs = {}) {
```

2020-11-29 20:45 UTC, obto commented on december.js
> +    static handleCommand(message_parts, otherArgs){
```suggestion
    static handleCommand(message_parts = [], otherArgs = {}){
```

2020-11-29 20:45 UTC, obto commented on december.js
> +effectsbtn = $('<button id="effectsbtn" class="btn btn-sm ' + (EFFECTSOFF ? 'btn-danger' : 'btn-default') + '" title="Turn off effects">Effects OFF</button>')
```suggestion
$('<button id="effectsbtn" class="btn btn-sm ' + (EFFECTSOFF ? 'btn-danger' : 'btn-default') + '" title="Turn off effects">Effects OFF</button>')
```

2020-11-29 20:58 UTC, obto commented on december.js
> +class CustomTextTriggers {
```suggestion
/**
 * To add a new effect create a class like so:
 class YourNewEffect {
  static command = '/your-command';

  constructor() {

  }

  init() {
  }

  handleCommand(message_parts = [], other_args = {}) {

  }

  enable() {}
  disable() {}
  stop() {}
}

Then add it to the `effects` static variable below
*/
class CustomTextTriggers {
```

2020-11-30 02:28 UTC, merged